config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#index'

  resources :artists
  resources :songs
  resources :pages
  resources :devise
  resources :users
  resources :image
  

  default_url_options :host => '127.0.0.1',  port: 3000
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/image.rb
class Image < ActiveRecord::Base
	  mount_uploader :image, ImageUploader # Tells rails to use this uploader for this model.
      validates :name, presence: true # Make sure the owner's name is present.
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  #accepts_nested_attributes_for :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


 def index
   @artists = Artist.all
end

   def new
    @artist = Artist.new
  end

  def create
    if @artist = Artist.create(artist_params)
      redirect_to root_path
    else
      render :new
    end
      end

  def edit
   @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end


  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
  end

  def destroy
    @artist = Artist.find(params[:id])
    if @artist.destroy
      redirect_to root_path
    else
      redirect_to @artist
    end
  end



private

  def artist_params
    params.require(:artist).permit(
      :name , :birth_date
    )
  end

 end

app/controllers/image_controller.rb
class ImageController < ApplicationController

 def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)

    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
  end

private
  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end


  def new
    @song = Song.new
  end

  def edit
   @song = Song.find(params[:id])
  end

def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end


  def create
   if @song = Song.create(song_params)
      redirect_to root_path
    else
      render :new
    end
  end

def show
  @song = Song.find(params[:id])
end


  private

  def song_params
    params.require(:song).permit(:title, :release_date, :album, :artist_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def header(text)
  content_for(:header) { text.to_s }
end

end

app/helpers/artists_controller_helper.rb
module ArtistsControllerHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/views/artists/_artist.html.erb
<h4> <%= link_to artist.name , artist %></h4>
<h4> <%= artist.birth_date %></h4>


<p class="navigation">
   <span class="btn btn-default"><%= link_to "Back", root_path %></span>
   <span class="btn btn-default"><%= link_to "Edit", edit_artist_path(artist)%></span>
   <span class="btn btn-default"><%= link_to "Destroy", artist_path(artist), method: :delete %></span>
 </p>
 <br>

app/views/artists/edit.html.erb
<h1>Edit artist</h1>


<%= form_for(@artist) do |f| %>
 
    <%= f.label :name %>
    <%= f.text_field :name %>


    <%= f.label :birth_date %>
    <%= f.text_field :birth_date %>


    <%= f.submit "Save artist" %>

    <% end %>

app/views/artists/index.html.erb
<%= render @artists %>

app/views/artists/new.html.erb
<%= form_for(@artist) do |f| %>
 
    <%= f.label :name %>
    <%= f.text_field :name %>


    <%= f.label :birth_date %>
    <%= f.text_field :birth_date %>


    <%= f.submit "Save artist" %>

    <% end %>

app/views/artists/show.html.erb
<%= @artist.name %>
<br>
<%= @artist.birth_date %> 


<p class="navigation">
   <span class="btn btn-default"><%= link_to "Back", root_path %></span>
   <span class="btn btn-default"><%= link_to "Edit artist", edit_artist_path(@artist)%></span>
   <span class="btn btn-default"><%= link_to "Destroy artist", artist_path(@artist), method: :delete %></span>
 </p>

<br>
<br>
<br>


<%= @artist.songs.each do |song| %>


			<h4> Title of the song: <%= song.title %></h4>
			<h4> Date: <%= song.release_date %></h4>
			<h4> Album name: <%= song.album %></h4>



<br>
<br>

<p class="navigation">
   <span class="btn btn-default"><%= link_to "Back", root_path %></span>
   <span class="btn btn-default"><%= link_to "Edit song", edit_song_path(song)%></span>
   <span class="btn btn-default"><%= link_to "Destroy song", song_path(song), method: :delete %></span>
 </p>

<% end %>

app/views/image/create.html.erb
<h1>Image#create</h1>
<p>Find me in app/views/image/create.html.erb</p>

app/views/image/destroy.html.erb
<h1>Image#destroy</h1>
<p>Find me in app/views/image/destroy.html.erb</p>

app/views/image/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New Resume", new_resume_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td><%= link_to "Download Resume", resume.attachment_url %></td>
        <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/image/new.html.erb
<% if !@resume.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    $(document).ready(function () {
    var Transitions = [];
    var TransitionEvents = [];
    var $bg = $("#bg");

    Transitions.push(new $.SParallax.Transition("top", 0, -50, "px", $bg, 0, 2));
    $.SParallax(Transitions, TransitionEvents);
  });
</script>


</head>
<body class="container">
<h1>Welcome to Music database</h1>


<nav>
<ul>
      <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Sign up", new_user_registration_path%></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %>
        <li><%= link_to "New artist", new_artist_path %>
        <li><%= link_to "New song", new_song_path %>
                 <% else %>
         <li><%= link_to "Sign up", new_user_registration_path %></li> 
         <li><%= link_to "Login", new_user_session_path%></li>
 
        <% end %>


 
</ul>
</nav>



<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">




  <%= yield %>

</div>

</body>
</html>

app/views/pages/index.html.erb
  <div class="jumbotron">
    <div class="container">

    


<% if user_signed_in? %>
        <li>Now you can check our database regarding music </li>
        <li><%= link_to "Songs ", songs_path%></li>
        <li><%= link_to "Artists", artists_path%></li>
        <% else %>
          <li>Please login first </li>
         <% end %>


  

   

    </div>
  </div>

app/views/songs/edit.html.erb
<h1>ArtistsController#edit</h1>
<p>Find me in app/views/artists_controller/edit.html.erb</p>

app/views/songs/index.html.erb
<div class="row">

<% @songs.each do |song| %>

	
			<div class="col-xs-12 col-sm-6 col-md-3 box highlight"> 
			<h4> <%= link_to song.title , song %></h4>
			<h4> <%= song.release_date %></h4>
			<h4> <%= song.album %></h4>

<p class="navigation">
   <span class="btn btn-default"><%= link_to "Back", root_path %></span>
   <span class="btn btn-default"><%= link_to "Edit", edit_song_path(song)%></span>
   <span class="btn btn-default"><%= link_to "Destroy", song_path(song), method: :delete %></span>
 </p>
 <br>
<br>
<br>
</div>
<% end %>
</div>

app/views/songs/new.html.erb
<%= form_for(@song) do |f| %>
 
    <%= f.label :title %>
    <%= f.text_field :title %>


    <%= f.label :release_date %>
    <%= f.text_field :release_date %>

    <%= f.label :album %>
    <%= f.text_field :album %>

    <%= f.label :artist_id %>
    <%= f.collection_select :artist_id, Artist.all, :id, :name, prompt: true %>


    <%= f.submit "Save song" %>

   
    <% end %>

app/views/songs/show.html.erb
<p>
<h1> Name of the singer of the previous song: </h1>
</p>

<h4> <%= @song.title %></h4>

<h4> <%= link_to @song.artist.name , artists_path %> </h4>
<p> born on: <%= @song.artist.birth_date %></p>

<p class="navigation">
   <span class="btn btn-default"><%= link_to "Back", root_path %></span>
   <span class="btn btn-default"><%= link_to "Edit", edit_song_path(@song)%></span>
   <span class="btn btn-default"><%= link_to "Destroy", song_path(@song), method: :delete %></span>
 </p>